Add feature flags to support older ffmpeg versions
meh/rust-ffmpeg pull request #137
Opened 2020-12-17 05:28 UTC by shssoichiro

Currently, this crate will fail to compile if an older
version of the ffmpeg libraries are installed on the machine.
This change causes this crate to support FFMpeg 3.0 and newer
by default. Newer API features can be enabled by setting the
appropriate feature flag e.g. `ffmpeg_3_4`, although this
will cause the crate using this crate to fail to compile on
older versions of ffmpeg.

Most immediately, this is required for CI on
https://github.com/rust-av/av-metrics/pull/218 to function correctly,
as Github Actions includes Ubuntu Bionic, which only includes up to FFMpeg 3.4.

2020-12-19 08:40 UTC, meh requested changes

2020-12-19 08:40 UTC, meh commented on src/util/format/pixel.rs
> +    #[cfg(feature = "ffmpeg_4_1")]
What happened here?

2020-12-19 08:41 UTC, meh commented
How do the features work, I see stuff enabled only for specific versions but I think it should be incremental?

I support the endeavor.

2020-12-19 13:48 UTC, shssoichiro commented
In the Cargo.toml, each feature [inherits the previous version's feature flag](https://github.com/meh/rust-ffmpeg/pull/137/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R91). So e.g. 3.2 will automatically enable 3.1 and below. 3.3 will enable 3.2 and below. And so on.

2020-12-19 13:50 UTC, shssoichiro commented on src/util/format/pixel.rs
> +    #[cfg(feature = "ffmpeg_4_1")]
User input error. Fixed now.

2020-12-20 12:00 UTC, meh commented
Oh I right, I missed that part, sorry about that.

Sounds good then!

2020-12-20 12:02 UTC, merged