fix(format): skip `avio_open` when format has `AVFMT_NOFILE`
meh/rust-ffmpeg pull request #180
Opened 2023-10-30 18:25 UTC by encounter

Avoids creating empty files for parameterized output paths and similar. (e.g. `output_%v.m3u8` for HLS)

2023-10-30 20:52 UTC, tilpner requested changes

2023-10-30 20:52 UTC, tilpner commented on src/format/mod.rs
> +					return Ok(output);
This would skip the `Dictionary::own` below, causing a memory leak.

2023-10-30 20:52 UTC, tilpner commented on src/format/mod.rs
> +						if (output.format().flags() & Flags::NO_FILE) == Flags::NO_FILE {
These can be `output.format().flags().contains(Flags::NO_FILE)`.

2023-10-30 20:55 UTC, tilpner commented
Good catch, thanks for the PR :)

2023-10-31 14:41 UTC, encounter commented
Adjusted to resolve the dictionary leaks, thanks! I'm going to submit a follow-up PR to clean up the Dictionary disown/own uses further.

2024-01-20 13:48 UTC, merged